name: "Run CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-checks:
    uses: ./.github/workflows/job-checks.yml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
